### ISSUE TITLE
order of \not character reversed on unicodeit.net

### ISSUE THREAD

**Issue by rigille** [svenkreiss/unicodeit#55]
Typing
```
0 \not\in \mathbb{N}
```
I expected to get
```
0 ∉ ℕ
```
Instead I got
```
0 ̸∈ ℕ
```
and
```
0 \in\not \mathbb{N}
```
yields the expected result. So maybe the order of the `\not` character should be swapped with the next character?. By the way 0 ∈ ℕ hahha

**Comment by cemulate** [comment]
Just leaving some info after my own investigation:

```
\not\subset
```

produces 
```
\xCC\xB8\xE2\x8A\x82
```

Which renders incorrectly in most contexts as "̸⊂"

`\xCC\xB8` is a "combining long solidus overlay" and the rest is "subset of".
According to the standard combining characters should come after the original so, though is a faithful literal rendering of the input, it is not the "correct" or expected result.

This is why if you use
```
\subset\not
```

The literally-rendered result will be
```
\xE2\x8A\x82\xCC\xB8
```
Which contains the combining character after the subset character and produces the correct result: "⊄"

---

I see two options for a "fix":
* Catch situations in which a TeX code will render as a combining character and appropriately switch the order
* Catch common commands like `\not\subset` and render them as the existing unicode character for that combination, this could be rendered as the individual "not a subset of" character which has its own codepoint, instead of using combining characters.

**Comment by cemulate** [comment]
I submitted a PR #61 to handle cases like this.

**Comment by HDembinski** [comment]
This should be closed since the PR was merged.
